[features]
seeds = false
skip-lint = false

[programs.localnet]
solana_app = "AHpwncxAnUsYngmKQajpgrRjZP3Gz4ysZiLQqjWZoBWK"

[programs.devnet]
solana_app = "AHpwncxAnUsYngmKQajpgrRjZP3Gz4ysZiLQqjWZoBWK"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
set-local="solana config set --url localhost"
set-dev="solana config set --url devnet"
deploy-dev="anchor deploy --provider.cluster devnet"
extract-idl="mv ./target/idl/solana_app.json ../ROLL/src/constants/SolanaIDL.json"