[features]
seeds = false
skip-lint = false

[programs.localnet]
solana_app = "8gRyXMnjEkN9YtHefq9ngkbdPrhnPSaytZTvCdfRKreW"

[programs.devnet]
solana_app = "8gRyXMnjEkN9YtHefq9ngkbdPrhnPSaytZTvCdfRKreW"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
deploy-dev="anchor deploy --provider.cluster devnet"
extract-idl="mv ./target/idl/solana_app.json ../game1/RollTheDice-front/src/constants/SolanaIDL.json"